# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-08 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_External',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AddOnes',
            fields=[
                ('ID', models.CharField(default='00000', max_length=20, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Pricing', models.CharField(max_length=50)),
                ('Restrictions', models.TextField()),
                ('Status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='C_R_C_L_M',
            fields=[
                ('ID', models.CharField(default='00000', max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('ID', models.CharField(default='00000', max_length=20, primary_key=True, serialize=False)),
                ('ChannelName', models.CharField(max_length=20)),
                ('ChannelLink', models.URLField()),
                ('Status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('ID', models.CharField(default='00000', max_length=20, primary_key=True, serialize=False)),
                ('DefaultInformation', models.BooleanField()),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('SpokenLanguages', models.TextField()),
                ('ExistingWebsite', models.URLField()),
                ('Status', models.CharField(max_length=3)),
                ('CreationDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Distances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitType', models.CharField(max_length=10)),
                ('ByBus', models.CharField(max_length=50)),
                ('ByUnderground', models.CharField(max_length=50)),
                ('ByMotorway', models.CharField(max_length=50)),
                ('ByTrain', models.CharField(max_length=50)),
                ('ByAirport', models.CharField(max_length=50)),
                ('ByPort', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalCertificates',
            fields=[
                ('ID', models.CharField(default='00000', max_length=20, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='G_R_P_R',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=25)),
                ('ImageFile', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=20)),
                ('PostalCode', models.CharField(max_length=25)),
                ('Address', models.TextField()),
                ('Latitude', models.CharField(max_length=40)),
                ('Longitude', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('ID', models.CharField(default='00000', max_length=15, primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='M_B_R',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BadgesID', models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Badges')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=25)),
                ('Phone', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='P_R_H',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_R_C_L_M_ID', models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.C_R_C_L_M')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=25)),
                ('Description', models.TextField()),
                ('ShowAddress', models.BooleanField()),
                ('Availability', models.BooleanField()),
                ('ManagerID', models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Manager')),
            ],
        ),
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('ID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=10)),
                ('Description', models.TextField()),
                ('StartDate', models.DateTimeField()),
                ('Duration', models.CharField(max_length=20)),
                ('PropertyID', models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Property')),
            ],
        ),
        migrations.CreateModel(
            name='Rents',
            fields=[
                ('ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('StartDate', models.DateTimeField()),
                ('EndDate', models.DateTimeField()),
                ('Rate', models.CharField(max_length=50)),
                ('BookAbility', models.CharField(max_length=10)),
                ('PolicyType', models.CharField(max_length=20)),
                ('ExtraCharge', models.CharField(max_length=50)),
                ('SeasonType', models.CharField(max_length=30)),
                ('CurrencyType', models.CharField(max_length=30)),
                ('RentType', models.CharField(max_length=30)),
                ('Notes', models.TextField()),
                ('PropertyID', models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Property')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('ID', models.CharField(default='00000', max_length=20, primary_key=True, serialize=False)),
                ('ReviewSources', models.TextField()),
                ('ReviewStatus', models.CharField(max_length=20)),
                ('PropertyID', models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Property')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('ID', models.CharField(default='00000', max_length=20, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=25)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='p_r_h',
            name='PropertyID',
            field=models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Property'),
        ),
        migrations.AddField(
            model_name='p_r_h',
            name='RegistrationsID',
            field=models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Registrations'),
        ),
        migrations.AddField(
            model_name='m_b_r',
            name='ManagerID',
            field=models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Manager'),
        ),
        migrations.AddField(
            model_name='m_b_r',
            name='RegistrationsID',
            field=models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Registrations'),
        ),
        migrations.AddField(
            model_name='login',
            name='RoleID',
            field=models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Roles'),
        ),
        migrations.AddField(
            model_name='location',
            name='PropertyID',
            field=models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Property'),
        ),
        migrations.AddField(
            model_name='g_r_p_r',
            name='GalleryID',
            field=models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Gallery'),
        ),
        migrations.AddField(
            model_name='g_r_p_r',
            name='PropertyID',
            field=models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Property'),
        ),
        migrations.AddField(
            model_name='g_r_p_r',
            name='RentsID',
            field=models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Rents'),
        ),
        migrations.AddField(
            model_name='g_r_p_r',
            name='ReviewsID',
            field=models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Reviews'),
        ),
        migrations.AddField(
            model_name='externalcertificates',
            name='PropertyID',
            field=models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Property'),
        ),
        migrations.AddField(
            model_name='distances',
            name='PropertyID',
            field=models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Property'),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='PropertyID',
            field=models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Property'),
        ),
        migrations.AddField(
            model_name='channel',
            name='ManagerID',
            field=models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Manager'),
        ),
        migrations.AddField(
            model_name='c_r_c_l_m',
            name='ChannelID',
            field=models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Channel'),
        ),
        migrations.AddField(
            model_name='c_r_c_l_m',
            name='ContactID',
            field=models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.ContactInformation'),
        ),
        migrations.AddField(
            model_name='c_r_c_l_m',
            name='LoginID',
            field=models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Login'),
        ),
        migrations.AddField(
            model_name='c_r_c_l_m',
            name='RolesID',
            field=models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Roles'),
        ),
        migrations.AddField(
            model_name='badges',
            name='PropertyID',
            field=models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Property'),
        ),
        migrations.AddField(
            model_name='addones',
            name='PropertyID',
            field=models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Property'),
        ),
        migrations.AddField(
            model_name='add_external',
            name='AddOnsID',
            field=models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.AddOnes'),
        ),
        migrations.AddField(
            model_name='add_external',
            name='ExternalCertificatesID',
            field=models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.ExternalCertificates'),
        ),
    ]
