# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-08 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='P_D_L',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DistancesID', models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Distances')),
                ('LocationID', models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Location')),
                ('PropertyID', models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Property')),
            ],
        ),
    ]
