# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-10 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20180710_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_B_R_C_R_L',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BadgesID', models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Badges')),
                ('ContactInformationID', models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.ContactInformation')),
                ('LoginID', models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Login')),
                ('ManagerID', models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Manager')),
                ('RegistrationsID', models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Registrations')),
                ('RolesID', models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Roles')),
            ],
        ),
        migrations.RemoveField(
            model_name='m_b_r',
            name='BadgesID',
        ),
        migrations.RemoveField(
            model_name='m_b_r',
            name='ManagerID',
        ),
        migrations.RemoveField(
            model_name='m_b_r',
            name='RegistrationsID',
        ),
        migrations.DeleteModel(
            name='M_B_R',
        ),
    ]
