# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-10 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20180710_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='L_C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChannelID', models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Channel')),
                ('LoginID', models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Login')),
            ],
        ),
        migrations.RemoveField(
            model_name='c_r_c_l_m',
            name='ChannelID',
        ),
        migrations.RemoveField(
            model_name='c_r_c_l_m',
            name='ContactID',
        ),
        migrations.RemoveField(
            model_name='c_r_c_l_m',
            name='LoginID',
        ),
        migrations.RemoveField(
            model_name='c_r_c_l_m',
            name='RolesID',
        ),
        migrations.RemoveField(
            model_name='p_r_h',
            name='C_R_C_L_M_ID',
        ),
        migrations.DeleteModel(
            name='C_R_C_L_M',
        ),
    ]
