# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-10 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20180710_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='P_E_R',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExternalCertificatesID', models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.ExternalCertificates')),
                ('PropertyID', models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Property')),
                ('RegistrationsID', models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='db.Registrations')),
            ],
        ),
        migrations.RemoveField(
            model_name='p_r_h',
            name='PropertyID',
        ),
        migrations.RemoveField(
            model_name='p_r_h',
            name='RegistrationsID',
        ),
        migrations.DeleteModel(
            name='P_R_H',
        ),
    ]
